Controllers/PanelimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using mvcKutuphaneP.Models.Entitiy;
namespace mvcKutuphaneP.Controllers
{
    public class PanelimController : Controller
    {
        // GET: Panelim
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        [Authorize]
        public ActionResult Index()
        {
            var uyemail = (string)Session["Mail"];
            var degerler = db.TBLUYELER.FirstOrDefault(z => z.MAIL == uyemail);
            return View(degerler);
        }
        [HttpPost]
        public ActionResult Index2(TBLUYELER p)
        {
            var kullanici = (string)Session["Mail"];
            var uye = db.TBLUYELER.FirstOrDefault(x => x.MAIL == kullanici);
            uye.SIFRE = p.SIFRE;
            uye.AD = p.AD;
            uye.FOTOGRAF = p.FOTOGRAF;
            uye.OKUL = p.OKUL;
            uye.KULLANICIADI = p.KULLANICIADI;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Kitaplarim()
        {
            var kullanici = (string)Session["Mail"];
            var id = db.TBLUYELER.Where(x => x.MAIL == kullanici.ToString()).Select(z => z.ID).FirstOrDefault();
            var degerler = db.TBLHAREKET.Where(x => x.UYE == id).ToList();
            return View(degerler);
        }
        public ActionResult Duyurular()
        {
            var duyurulistesi = db.TBLDUYURULAR.ToList();
            return View(duyurulistesi);
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("GirisYap","Login");
        }
    }
}

Views/Panelim/Duyurular.cshtml
@using mvcKutuphaneP.Models.Entitiy;
@model List<TBLDUYURULAR>
@{
    ViewBag.Title = "Duyurular";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}

<h2>Duyurular</h2>

<table class="table table-bordered">
    <tr>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>İçerik</th>
    </tr>
    @foreach (var prs in Model)
    {
        <tr>
            <td>@prs.KATEGORI</td>
            <td>@Convert.ToDateTime(prs.TARIH).ToString("dd/MM/yyyy")</td>
            <td>@prs.ICERİK</td>
        </tr>
    }
</table>

Views/Panelim/Index.cshtml
@model mvcKutuphaneP.Models.Entitiy.TBLUYELER
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}

<h2>Kütüphane Üye Profil Bilgileri</h2>

@using (Html.BeginForm("Index2", "Panelim", FormMethod.Post))
{
<table class="table table-hover" style="margin-top:30px">

    <tr>
        <td>
            <label style="font-weight:bolder">Mail Adresi: </label>  @HttpContext.Current.User.Identity.Name
        </td>
    </tr>


    <tr>
        <td>
            @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })
        </td>

    </tr>
    <tr>
        <td>
            @Html.TextBoxFor(x => x.KULLANICIADI, new { @class = "form-control" })
        </td>

    </tr>
    <tr>
        <td>
            @Html.TextBoxFor(x => x.SIFRE, new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.TextBoxFor(x => x.FOTOGRAF, new { @class = "form-control" })
        </td>

    </tr>
    <tr>
        <td>
            @Html.TextBoxFor(x => x.OKUL, new { @class = "form-control" })
        </td>

    </tr>
    <tr>
        <td>
            <button class="btn btn-warning">Şifre Güncelle</button>
        </td>
    </tr>
</table>
}

Views/Panelim/Kitaplarim.cshtml
@using mvcKutuphaneP.Models.Entitiy
@model List<TBLHAREKET>
@{
    ViewBag.Title = "Kitaplarim";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}
<br />
<h2>Kitap Geçmişim</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Kitap Adı</th>
        <th>Alış Tarihi</th>
        <th>Üye İade Tarihi</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.TBLKITAP.AD</td>
            <td>@Convert.ToDateTime(k.ALISTARIH).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(k.UYEGETIRTARIH).ToString("dd/MM/yyyy")</td> 
        </tr>
    }
</table>