Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvcKutuphaneP.Models.Entitiy;
namespace mvcKutuphaneP.Controllers
{
    public class DuyuruController : Controller
    {
        // GET: Duyuru
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLDUYURULAR.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniDuyuru()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniDuyuru(TBLDUYURULAR t)
        {
            db.TBLDUYURULAR.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruSil(int id)
        {
            var duyuru = db.TBLDUYURULAR.Find(id);
            db.TBLDUYURULAR.Remove(duyuru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruDetay(TBLDUYURULAR p)
        {
            var duyuru = db.TBLDUYURULAR.Find(p.ID);
            return View("DuyuruDetay", duyuru);
        }
        public ActionResult DuyuruGuncelle(TBLDUYURULAR t)
        {
            var duyuru = db.TBLDUYURULAR.Find(t.ID);
            duyuru.KATEGORI = t.KATEGORI;
            duyuru.ICERİK = t.ICERİK;
            duyuru.TARIH = t.TARIH;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Duyuru/DuyuruDetay.cshtml
@model mvcKutuphaneP.Models.Entitiy.TBLDUYURULAR
@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        <label>Duyuru Kategori</label>
        @Html.TextBoxFor(k => k.KATEGORI, new { @class = "form-control" })
        <br />
        <label>Duyuru İçerik</label>
        @Html.TextAreaFor(k => k.ICERİK, new { @class = "form-control" })
        <br />
        <label>Duyuru Tarih</label>
        @Html.TextBoxFor(k => k.TARIH, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

Views/Duyuru/Index.cshtml
@using mvcKutuphaneP.Models.Entitiy;
@model List<TBLDUYURULAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
    string renk = "";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<h2>Duyurular</h2>

<table class="table table-bordered">
    <tr>
        <th>Duyuru No</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>İçerik</th>
    </tr>
    @foreach (var prs in Model)
    {

        if (prs.KATEGORI == "Diğer")
        {
            renk = "bg-info text-white";
        }
        if (prs.KATEGORI == "Yeni Kitap")
        {
            renk = "bg-warning text-white";
        }
        if (prs.KATEGORI == "İletişim")
        {
            renk = "bg-success text-white";
        }
        if (prs.KATEGORI == "Kitapları Geciktirmeyin")
        {
            renk = "bg-danger text-white";
        }
        <tr class="@renk">
            <td>@prs.ID</td>
            <td>@prs.KATEGORI</td>
            <td>@Convert.ToDateTime(prs.TARIH).ToString("dd/MM/yyyy")</td>
            <td><a href="/Duyuru/DuyuruSil/@prs.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Duyuru/DuyuruDetay/@prs.ID" class="btn btn-default" style="background-color:skyblue">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Duyuru/YeniDuyuru/" class="btn btn-primary">Yeni Duyuru Ekle</a>

Views/Duyuru/YeniDuyuru.cshtml
@model mvcKutuphaneP.Models.Entitiy.TBLDUYURULAR
@{
    ViewBag.Title = "YeniDuyuru";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Duyuru Kategorisi</label>
        @Html.TextBoxFor(x => x.KATEGORI, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Duyuru içerik</label>
        @Html.TextBoxFor(x => x.ICERİK, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Duyuru Tarih</label>
        @Html.TextBoxFor(x => x.TARIH, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="Btn1">Duyuru Ekle</button>
    </div>
</form>