Controllers/OduncController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvcKutuphaneP.Models.Entitiy;

namespace mvcKutuphaneP.Controllers
{
    public class OduncController : Controller
    {
        // GET: Odunc
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLHAREKET.Where(x => x.ISLEMDURUM == false).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult OduncVer()
        {
            List<SelectListItem> deger1 = (from x in db.TBLUYELER.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.AD + " " + x.SOYAD,
                                               Value = x.ID.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from y in db.TBLKITAP.Where(x => x.DURUM == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.AD,
                                               Value = y.ID.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from z in db.TBLPERSONEL.ToList()
                                           select new SelectListItem
                                           {
                                               Text = z.PERSONEL,
                                               Value = z.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult OduncVer(TBLHAREKET p)
        {
            var d1 = db.TBLUYELER.Where(x => x.ID == p.TBLUYELER.ID).FirstOrDefault();
            var d2 = db.TBLKITAP.Where(y => y.ID == p.TBLKITAP.ID).FirstOrDefault();
            var d3 = db.TBLPERSONEL.Where(z => z.ID == p.TBLPERSONEL.ID).FirstOrDefault();
            p.TBLUYELER = d1;
            p.TBLKITAP = d2;
            p.TBLPERSONEL = d3;
            db.TBLHAREKET.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Odunciade(TBLHAREKET p)
        {
            var odn = db.TBLHAREKET.Find(p.ID);
            DateTime d1 = DateTime.Parse(odn.IADETARIH.ToString());
            DateTime d2 = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan d3 = d2 - d1;
            ViewBag.dgr = d3.TotalDays;
            return View("Odunciade", odn);
        }
        public ActionResult OduncGuncelle(TBLHAREKET p)
        {
            var hrk = db.TBLHAREKET.Find(p.ID);
            hrk.UYEGETIRTARIH = p.UYEGETIRTARIH;
            hrk.ISLEMDURUM = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Odunc/Index.cshtml
@using mvcKutuphaneP.Models.Entitiy
@model List<TBLHAREKET>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<h2>Ödünç Kitap Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th>İşlem ID</th>
        <th>Kitap Adı</th>
        <th>Üye</th>
        <th>Personel</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
        <th>İade Al</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.ID</td>
            <td>@k.TBLKITAP.AD</td>
            <td>@k.TBLUYELER.AD&nbsp @k.TBLUYELER.SOYAD</td>
            <td>@k.TBLPERSONEL.PERSONEL</td>
            <td>@Convert.ToDateTime(k.ALISTARIH).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(k.IADETARIH).ToString("dd/MM/yyyy")</td>
            <td><a href="/Odunc/Odunciade/@k.ID" class="btn btn-default" style="background-color:#68e9f9;color:white">Kitabı İade Et</a></td>
        </tr>
    }
</table>

Views/Odunc/OduncVer.cshtml
@model mvcKutuphaneP.Models.Entitiy.TBLHAREKET
@{
    ViewBag.Title = "OduncVer";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Üye ID</label>
        @*@Html.TextBoxFor(k => k.UYE, new { @class = "form-control" })*@
        @Html.DropDownListFor(k => k.TBLUYELER.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = " form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap ID</label>
        @*@Html.TextBoxFor(k => k.KITAP, new { @class = "form-control" })*@
        @Html.DropDownListFor(k => k.TBLKITAP.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = " form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Personel ID</label>
        @*@Html.TextBoxFor(k => k.PERSONEL, new { @class = "form-control" })*@
         @Html.DropDownListFor(k => k.TBLPERSONEL.ID, (List<SelectListItem>)ViewBag.dgr3, new { @class = " form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Alış Tarihi</label>
        <input type="text" class="form-control" name="ALISTARIH" value="@DateTime.Now.ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <label>Kitap İade Tarihi</label>
        <input type="text" class="form-control" name="IADETARIH" value="@DateTime.Now.AddDays(7).ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-group" style="background-color:#c583ff;color:white">Kitabı Ödünç Ver</button>
        <input type="hidden" value="False" name="ISLEMDURUM" />
    </div>
</form>

Views/Odunc/Odunciade.cshtml
@model mvcKutuphaneP.Models.Entitiy.TBLHAREKET
@{
    ViewBag.Title = "Odunciade";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("OduncGuncelle", "Odunc", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <label>Hareket ID</label>
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.TBLKITAP.AD, new { @class = "form-control" })
        <br />
        <label>Üye</label>
        @Html.TextBoxFor(k => k.TBLUYELER.AD, new { @class = "form-control" })
        <br />
        <label>Personel</label>
        @Html.TextBoxFor(k => k.TBLPERSONEL.PERSONEL, new { @class = "form-control" })
        <br />
        <label>Alış tarihi</label>
        @Html.TextBoxFor(k => k.ALISTARIH, "{0:dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>Normal İade tarihi</label>
        @Html.TextBoxFor(k => k.IADETARIH, "{0:dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>Üyenin Getirdiği Tarih</label>
        <input type="text" class="form-control" name="UYEGETIRTARIH " value="@DateTime.Now.ToShortDateString()" />
        <br />
        <label>Geç Gelen Gün Sayısı</label>
        <input type="text"class="form-control"id="Gecinput"value="@ViewBag.dgr" />
    </div>
    <div>
        <button class="btn btn-group" style="background-color: #68e9f9; color: white">Ödünç Kitabı Geri Al</button>
    </div>
}